model:
  base_learning_rate: 4.5e-6
  target: taming.models.vq_test.VQModel
  params:
    scale: 1 # the scale of codebook length
    partitions: 4 # the groups of codebook 
    embed_dim: 256
    n_embed: 1024
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /data1/lianjunrong/dataset/ADE20K/ADE20K_2021_17_01/images/ADE/train1.txt
        size: 256
        # crop_size: 256
    validation:
      target: taming.data.custom.CustomTest
      params: 
        test_images_list_file: /data1/lianjunrong/dataset/ADE20K/ADE20K_2021_17_01/images/ADE/test1.txt
        size: 256
        # crop_size: 256


